spring:
  application:
    name: ai-demo

server:
  port: 8081
  servlet:
    context-path: /api

langchain4j:
  community:
    dashscope:
      chat-model:
        api-key: sk-3d2abcc406764ac5a535d1e1f82887e3
        model-name: qwen-max
        temperature: 0.7
        max-tokens: 4096
        enable-search: true
        is-multimodal-model: true

      streaming-chat-model:
        api-key: sk-3d2abcc406764ac5a535d1e1f82887e3
        model-name: qwen-max
        temperature: 0.7
        max-tokens: 4096
        enable-search: true